services:
  mongo:
    image: mongo:8.0.3
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - mynet

  redis:
    image: redis:7.4.1
    ports:
      - "6379:6379"
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
